version: "3"
services:
  init_db:
    build: init_db/
    command: python ./init.py
    depends_on:
      - "db"
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'admin_db'
      MYSQL_PASSWORD: 'admin_db'
      MYSQL_ROOT_PASSWORD: 'admin_db'
    ports:
      - '4000:3306'
    expose:
      - '4000'
    volumes:
      - my-db:/var/lib/mysql
  web:
    build: http/
    depends_on:
      - "init_db"
    ports:
      - '5000:5000'

volumes:
  my-db:
